title: Open Japanese
email: openjapanese@joshmangiola.com
description: >- # this means to ignore newlines until "baseurl:"
  Open Japanese is a resource containing information about learning Japanese that is free
  to use and open to contributions.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://openjapanese.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: joshm998
github_username:  joshm998

# Build settings
remote_theme: pdmosses/just-the-docs@rec-nav-2
plugins:
  - jekyll-feed
  - jekyll-remote-theme

search_enabled: true

search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false

collections:
  # Define a collection named "docs", its documents reside in the "_docs" directory
  docs:
    permalink: "/:path/"
    output: true
    title: 'Docs'
  grammar:
    permalink: "/:collection/:path/"
    output: true
    title: Grammar

just_the_docs:
  # Define which collections are used in just-the-docs
  collections:
    grammar:
      name: Grammar
    docs:
      name: Docs

defaults:
  -
    scope:
      # an empty string here means all files in the project - THAT BREAKS JTD
      # This gets things in all the collections
      # It's a hack around this bug: https://github.com/pmarsceill/just-the-docs/issues/472
      path: "_*"
    values:
      layout: "page"
      date: "1970-01-01"

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/joshm998/open-japanese" # the github URL for your repo
gh_edit_branch: "master" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "edit" # "tree" or "edit" if you want the user to jump into the editor immediately

